apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315861220225:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-XZW1SK3L4PZ7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-14T10:28:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1843"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2a28bf00-a654-47fe-bd40-c69484c7a93d
