apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::209118123340:role/eksctl-simple-jwt-api-nodegroup-m-NodeInstanceRole-E5D4YBOD8WSU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters      
      rolearn: arn:aws:iam::209118123340:role/UdacityFlaskDeployCBKubectlRole
      username: perfect
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-22T07:11:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1438"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5f6c5f8e-c1ee-40b7-bfd0-2163debd3869
