apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::485455245878:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1B2Q0HFURNFIB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::485455245878:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-01T15:56:54Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-03-01T15:56:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1616"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4feffac4-539c-42d5-95ff-8101e1f0aa81
