apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::430055510977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KIB7DA1VIW2D
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::430055510977:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-11T18:24:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1318"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6e88e315-3b38-4c9c-b132-0d520fae553b
