apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::209118123340:role/eksctl-simple-jwt-api-nodegroup-m-NodeInstanceRole-JB1H3IUG9TYN
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::209118123340:role/UdacityFlaskDeployCBKubectlRole
      username: build      
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-22T09:03:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1332"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a9bedda9-6532-40fa-a95b-7070cb7966ff
