apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::982897313602:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OP5B1V299Q1W
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::982897313602:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-08T04:02:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "761"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 94cdfa6c-60f1-11ea-9c3f-0685fcd0e19e
