apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::934693926325:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ODB397D1BP5N
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-31T10:12:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1637"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f63bb861-3ab8-42eb-aeaa-87a79e3348b8
