# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.



apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::416107867172:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Z5VGL0Y4FXR5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::416107867172:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-04T07:52:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3839"
  uid: 3f73d638-6a31-4b80-89ea-96a5278cad1d