apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::257552941228:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EOQMPAZTWDE2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::257552941228:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-17T04:31:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1520"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d301fbb3-21fc-4e9b-a8a3-3b37054e3f6e
