apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::090294738848:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-G2C3QL24L3HC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::090294738848:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-14T23:43:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1324"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e03aa2ef-362d-4ee6-a5c3-53759aeb4cf5
