apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::090294738848:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-N072J9YVAJVF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::090294738848:role/UdacityFlaskDeployCBKubectlRole
      username: perfect
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-15T21:04:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1352"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 36bf4166-84cf-4e7d-8a06-f6e4d56eefce
