apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::118102576004:role/UdacityFlaskDeployCBKubectlRole
    username: build
    groups:
      - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::118102576004:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EAFNI16YJPII
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-27T07:56:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2373"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a53743c3-9cf1-4b59-a235-980338f89c3d
