name: Create AWS infrastructure
on:
  push:
    branches:
      - master 
jobs:
  setup_roles_and_policies:
    runs-on: ubuntu-latest
    environment:
      name: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Setup the runner
        run: |
          sudo apt update -y
          sudo apt install -y jq

      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Setup AWS credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID}
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY}
          aws configure set default.region us-west-1

      - name: Creates the role for the trust policy
        run: |
          aws iam create-role --role-name cv-eks-cluster-role --assume-role-policy-document file://${GITHUB_WORKSPACE}/eksk8s/eks-cluster-trust-policy.json

      - name: Attaches the policy to the new role
        run: |
          aws iam put-role-policy --role-name cv-eks-cluster-role --policy-name eks-cluster-policy --policy-document file://${GITHUB_WORKSPACE}/eksk8s/eks-cluster-policy.json
