name: Create AWS infrastructure
on:
  push:
    branches:
      - infrastructure
jobs:
  setup_roles_and_policies:
    runs-on: ubuntu-latest
    environment:
      name: develop
    env:
      CLUSTER_ROLE_NAME: ${{ vars.CLUSTER_ROLE_NAME }}
      CLUSTER_POLICY_NAME: ${{ vars.CLUSTER_POLICY_NAME }}
      NODEGROUP_ROLE_NAME: ${{ vars.NODEGROUP_ROLE_NAME }}
      NODEGROUP_POLICY_NAME: ${{ vars.NODEGROUP_POLICY_NAME }}
      CODEPIPELINE_ROLE_NAME: ${{ vars.CODEPIPELINE_ROLE_NAME }}
      CODEPIPELINE_POLICY_NAME: ${{ vars.CODEPIPELINE_POLICY_NAME }}
      CODEBUILD_ROLE_NAME: ${{ vars.CODEBUILD_ROLE_NAME }}
      CODEBUILD_POLICY_NAME: ${{ vars.CODEBUILD_POLICY_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Creates the role that will assume the trust policy to deal with the cluster
        run: aws iam create-role --role-name ${CLUSTER_ROLE_NAME} --assume-role-policy-document file://${GITHUB_WORKSPACE}/eksk8s/eks-cluster-trust-policy.json

      - name: Attaches the policy to the cluster role
        run: aws iam put-role-policy --role-name ${CLUSTER_ROLE_NAME} --policy-name ${CLUSTER_POLICY_NAME} --policy-document file://${GITHUB_WORKSPACE}/eksk8s/eks-cluster-policy.json

      - name: Creates the role that will assume the trust policy to deal with the node-group
        run: aws iam create-role --role-name ${NODEGROUP_ROLE_NAME} --assume-role-policy-document file://${GITHUB_WORKSPACE}/eksk8s/eks-nodegroup-trust-policy.json

      - name: Attaches the policy for the node-group role
        run: aws iam put-role-policy --role-name ${NODEGROUP_ROLE_NAME} --policy-name ${NODEGROUP_POLICY_NAME} --policy-document file://${GITHUB_WORKSPACE}/eksk8s/eks-nodegroup-policy.json

      - name: Create the role that will assume the trust policy to deal with the codepipeline service
        run: aws iam create-role --role-name ${CODEPIPELINE_ROLE_NAME} --assume-role-policy-document file://${GITHUB_WORKSPACE}/eksk8s/codepipeline-trust-policy.json

      - name: Attaches the policy for the codepipeline role
        run: aws iam put-role-policy --role-name ${CODEPIPELINE_ROLE_NAME} --policy-name ${CODEPIPELINE_POLICY_NAME} --policy-document file://${GITHUB_WORKSPACE}/eksk8s/codepipeline-policy.json

      - name: Create the role that will assume the trust policy to deal with the codebuild service
        run: aws iam create-role --role-name ${CODEBUILD_ROLE_NAME} --assume-role-policy-document file://${GITHUB_WORKSPACE}/eksk8s/codebuild-trust-policy.json

      - name: Attaches the policy for the codebuild role
        run: aws iam put-role-policy --role-name ${CODEBUILD_ROLE_NAME} --policy-name ${CODEBUILD_POLICY_NAME} --policy-document file://${GITHUB_WORKSPACE}/eksk8s/codebuild-policy.json

  create_the_cluster:
    runs-on: ubuntu-latest
    needs: setup_roles_and_policies
    environment:
      name: develop
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_TRUST_OWNERS: ${{ secrets.GPG_TRUST_OWNERS }}
      RECIPIENT_ID: ${{ secrets.RECIPIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Setup the runner
        run: |
          sh ${GITHUB_WORKSPACE}/.github/scripts/eksctl-install.sh
          sh ${GITHUB_WORKSPACE}/.github/scripts/gpg-install.sh

      - name: Setup the keys used to create the k8s cluster
        run: |
          mkdir ${HOME}/.ssh/
          echo ${SSH_PRIVATE_KEY} > ${HOME}/.ssh/k8s
          echo ${SSH_PUBLIC_KEY} > ${HOME}/.ssh/k8s.pub

      - name: Import the gpg components
        run: |
          echo ${GPG_TRUST_OWNERS} | base64 --decode > trust-file
          gpg --import-ownertrust < trust-file
          echo ${GPG_PUBLIC_KEY} | base64 --decode | gpg --import
          echo ${GPG_PRIVATE_KEY} | base64 --decode | gpg --import --batch

      - name: Creates the k8s cluster using eksctl
        run: eksctl create cluster -f ${GITHUB_WORKSPACE}/eksk8s/cluster-config.yaml

      - name: Encrypts the kubeconfig file
        run: gpg --encrypt -r ${RECIPIENT_ID} --output kube_config.gpg ${HOME}/.kube/config

      - name: Pushes kubeconfig artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: kube_config.gpg
          path: ${{ github.workspace }}
