name: Generate KMS (Key Management System) and store the ARN

on:
  push:
    branches:
      - secrets

jobs:
  generate_kms_key:
    runs-on: ubuntu-latest
    environment:
        name: develop
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLUSTER_ROLE_NAME: cv-eks-cluster-role
        CLUSTER_POLICY_NAME: cv-eks-cluster-policy
        NODEGROUP_ROLE_NAME: cv-eks-nodegroup-role
        NODEGROUP_POLICY_NAME: cv-eks-nodegroup-policy
        CODEPIPELINE_ROLE_NAME: cv-codepipeline-role
        CODEPIPELINE_POLICY_NAME: cv-codepipeline-policy
        CODEBUILD_ROLE_NAME: cv-codebuild-role
        CODEBUILD_POLICY_NAME: cv-codebuild-policy
    steps:
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Generate KMS key
        run: |
          key_id=$(aws kms create-key --query KeyMetadata.KeyId --output text)
          echo "::set-output name=kms_key_id::$key_id"
          key_arn=$(aws kms describe-key --key-id $key_id --query KeyMetadata.Arn --output text)
          echo "::set-output name=kms_key_arn::$key_arn"

      - name: Save the KVM key in GH secrets
        run: |
          echo "::add-mask::$kms_key_arn"
          echo "::set-env name=KMS_KEY_ARN::$kms_key_arn"
          echo "KMS_KEY_ARN=$kms_key_arn" >> $GITHUB_ENV
          echo "::set-output name=kms_key_arn::$kms_key_arn"
